// Code generated by sqlc. DO NOT EDIT.

package model

import (
	"time"
)

type ScmAccount struct {
	UserID       int32  `json:"userID"`
	UserName     string `json:"userName"`
	UserAccount  string `json:"userAccount"`
	UserEmail    string `json:"userEmail"`
	UserPassword string `json:"userPassword"`
}

type ScmOrder struct {
	OrderID     int32      `json:"orderID"`
	OrderDate   *time.Time `json:"orderDate"`
	Etd         *time.Time `json:"etd"`
	OrderMemo   *string    `json:"orderMemo"`
	ProductID   *int       `json:"productID"`
	RegDatetime time.Time  `json:"regDatetime"`
	RegUserID   *int       `json:"regUserID"`
	ModDatetime time.Time  `json:"modDatetime"`
	ModUserID   *int       `json:"modUserID"`
}

type ScmProduct struct {
	ProductID      int32     `json:"productID"`
	ProductUnit    *string   `json:"productUnit"`
	ManufacturerID *int      `json:"manufacturerID"`
	ProductName    *string   `json:"productName"`
	RegDatetime    time.Time `json:"regDatetime"`
	RegUserID      *int      `json:"regUserID"`
	ModDatetime    time.Time `json:"modDatetime"`
	ModUserID      *int      `json:"modUserID"`
}

type ScmProductSize struct {
	RowID       int32  `json:"rowID"`
	ProductID   int32  `json:"productID"`
	Size        string `json:"size"`
	BarcodeUnit string `json:"barcodeUnit"`
}
