// Code generated by sqlc. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
)

type Querier interface {
	CheckDuplicateAccount(ctx context.Context, userAccount string) ([]string, error)
	CheckDuplicateEmail(ctx context.Context, userEmail string) ([]string, error)
	CheckDuplicateProductUnit(ctx context.Context, productUnit *string) ([]*string, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteUser(ctx context.Context, userID int32) error
	GetProductFromProductID(ctx context.Context, productID int32) (ScmProduct, error)
	GetProductFromProductUnit(ctx context.Context, productUnit *string) (interface{}, error)
	GetProductIDFromUser(ctx context.Context, userID int32) ([]int32, error)
	GetSignedId(ctx context.Context, userAccount string) (int32, error)
	GetUser(ctx context.Context, userID int32) (ScmAccount, error)
	ListUser(ctx context.Context) ([]ListUserRow, error)
	UpdateProductName(ctx context.Context, arg UpdateProductNameParams) error
	UpdateProductUnit(ctx context.Context, arg UpdateProductUnitParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
