// Code generated by sqlc. DO NOT EDIT.

package tutorial

import (
	"database/sql"
)

type ScmAccount struct {
	UserID       int32
	UserName     string
	UserAccount  string
	UserEmail    string
	UserPassword string
}

type ScmProduct struct {
	ProductID      int32
	ProductUnit    sql.NullString
	ManufacturerID sql.NullInt32
	ProductName    sql.NullString
	RegDatetime    sql.NullTime
}
